version: '3.8'

services:
  finaura:
    image: finaura:latest
    build:
      context: .
    container_name: finaura
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production
    restart: unless-stopped
